-- SPDX-License-Identifier: Apache-2.0
-- Generated from a fresh Laravel/MySQL migration by scripts/generate_rust_schema_baseline.sh.
-- Historical SQLx migration files are intentionally not replayed by the runtime.
SET FOREIGN_KEY_CHECKS=0;
CREATE TABLE `availability_windows` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `node_id` char(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `start_time` time NOT NULL,
  `end_time` time NOT NULL,
  `share` double NOT NULL DEFAULT '1',
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `availability_windows_node_id_index` (`node_id`),
  CONSTRAINT `availability_windows_node_id_foreign` FOREIGN KEY (`node_id`) REFERENCES `nodes` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `capabilities` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `node_id` char(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `intent` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `models` json NOT NULL,
  `max_tokens` int unsigned NOT NULL,
  `input_modalities` json DEFAULT NULL,
  `supported_profiles` json DEFAULT NULL,
  `quantization` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `inference_engine` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `capabilities_node_id_intent_index` (`node_id`,`intent`),
  KEY `capabilities_intent_index` (`intent`),
  CONSTRAINT `capabilities_node_id_foreign` FOREIGN KEY (`node_id`) REFERENCES `nodes` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `conformance_badges` (
  `badge_id` varchar(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `tier` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `subject_did` varchar(256) COLLATE utf8mb4_unicode_ci NOT NULL,
  `subject_component` varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL,
  `suite_version` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `passed_at` datetime NOT NULL,
  `expires_at` datetime NOT NULL,
  `test_results_url` varchar(512) COLLATE utf8mb4_unicode_ci NOT NULL,
  `issuer_did` varchar(256) COLLATE utf8mb4_unicode_ci NOT NULL,
  `verification_mode` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'self-attested',
  `sig` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `status` varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'active',
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`badge_id`),
  KEY `conformance_badges_subject_did_tier_status_index` (`subject_did`,`tier`,`status`),
  KEY `conformance_badges_expires_at_status_index` (`expires_at`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `credit_ip_gates` (
  `ip_address` varchar(45) COLLATE utf8mb4_unicode_ci NOT NULL,
  `last_allocation_at` timestamp NULL DEFAULT NULL,
  `allocation_count` int unsigned NOT NULL DEFAULT '0',
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`ip_address`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `credit_transactions` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `node_id` char(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `amount` decimal(15,4) NOT NULL,
  `type` enum('credit','debit') COLLATE utf8mb4_unicode_ci NOT NULL,
  `task_id` varchar(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `nonce` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `reason` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `expires_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `credit_transactions_nonce_unique` (`nonce`),
  KEY `credit_transactions_node_id_created_at_index` (`node_id`,`created_at`),
  KEY `credit_tx_expires_at_idx` (`expires_at`),
  CONSTRAINT `credit_transactions_node_id_foreign` FOREIGN KEY (`node_id`) REFERENCES `nodes` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `credits` (
  `node_id` char(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `balance` decimal(15,4) NOT NULL DEFAULT '0.0000',
  `free_credit_last_allocation_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`node_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `data_subject_actions` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `tracking_id` varchar(96) COLLATE utf8mb4_unicode_ci NOT NULL,
  `action` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `subject_hash` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `selector` json NOT NULL,
  `affected_counts` json DEFAULT NULL,
  `retention_reason` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `applied_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `data_subject_actions_tracking_id_unique` (`tracking_id`),
  KEY `data_subject_actions_action_applied_at_index` (`action`,`applied_at`),
  KEY `data_subject_actions_subject_hash_index` (`subject_hash`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `dispatch_usage_daily` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `usage_date` date NOT NULL,
  `mode` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `request_count` bigint unsigned NOT NULL DEFAULT '0',
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `dispatch_usage_daily_usage_date_mode_unique` (`usage_date`,`mode`),
  KEY `dispatch_usage_daily_usage_date_index` (`usage_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `iicp_telemetry_aggregates` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `window` varchar(8) COLLATE utf8mb4_unicode_ci NOT NULL,
  `metric` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `value` double DEFAULT NULL,
  `sample_count` int NOT NULL DEFAULT '0',
  `computed_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `iicp_telemetry_aggregates_window_metric_computed_at_index` (`window`,`metric`,`computed_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `iicp_telemetry_probes` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `probe_token_id` bigint unsigned DEFAULT NULL,
  `node_id` varchar(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `run_id` varchar(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `probe_id` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `probe_type` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `test_id` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `level` varchar(8) COLLATE utf8mb4_unicode_ci NOT NULL,
  `passed` tinyint(1) NOT NULL,
  `latency_ms` double DEFAULT NULL,
  `detail` text COLLATE utf8mb4_unicode_ci,
  `metadata` json DEFAULT NULL,
  `probed_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `iicp_telemetry_probes_probe_token_id_probed_at_index` (`probe_token_id`,`probed_at`),
  KEY `iicp_telemetry_probes_test_id_probed_at_index` (`test_id`,`probed_at`),
  KEY `iicp_telemetry_probes_node_id_probed_at_index` (`node_id`,`probed_at`),
  CONSTRAINT `iicp_telemetry_probes_probe_token_id_foreign` FOREIGN KEY (`probe_token_id`) REFERENCES `probe_tokens` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `node_address_history` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `node_id` char(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `ip_address` varchar(45) COLLATE utf8mb4_unicode_ci NOT NULL,
  `request_type` enum('register','heartbeat','other') COLLATE utf8mb4_unicode_ci NOT NULL,
  `observed_at` timestamp NOT NULL,
  PRIMARY KEY (`id`),
  KEY `node_address_history_node_id_index` (`node_id`),
  KEY `node_address_history_observed_at_index` (`observed_at`),
  CONSTRAINT `node_address_history_node_id_foreign` FOREIGN KEY (`node_id`) REFERENCES `nodes` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `node_event_chain_heads` (
  `chain_id` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `last_seq` bigint unsigned NOT NULL DEFAULT '0',
  `last_signature` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`chain_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
INSERT INTO `node_event_chain_heads` (`chain_id`, `last_seq`, `last_signature`, `created_at`, `updated_at`)
VALUES ('genesis', 0, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
CREATE TABLE `node_events` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `event_id` char(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `seq` bigint unsigned NOT NULL,
  `event_type` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `service_id` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `node_id` varchar(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ts_ms` bigint unsigned NOT NULL,
  `payload` json NOT NULL,
  `prev_hash` char(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `signature` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `node_events_event_id_unique` (`event_id`),
  UNIQUE KEY `node_events_seq_unique` (`seq`),
  KEY `node_events_seq_event_type_index` (`seq`,`event_type`),
  KEY `node_events_node_id_index` (`node_id`),
  KEY `node_events_service_id_index` (`service_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `node_health_observations` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `node_id` varchar(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `evaluator_did` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `score` double NOT NULL,
  `label` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `components` json DEFAULT NULL,
  `evaluated_at_ms` bigint unsigned NOT NULL,
  `event_id` char(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `node_health_observations_node_id_evaluator_did_unique` (`node_id`,`evaluator_did`),
  KEY `node_health_observations_node_id_index` (`node_id`),
  KEY `node_health_observations_evaluated_at_ms_index` (`evaluated_at_ms`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `nodes` (
  `id` char(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `endpoint` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `observed_source_ip` varchar(45) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `region` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `load` double NOT NULL DEFAULT '0',
  `active_jobs` int unsigned NOT NULL DEFAULT '0',
  `available` tinyint(1) NOT NULL DEFAULT '1',
  `relay_capable` tinyint(1) NOT NULL DEFAULT '0',
  `backend` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `health_models` json DEFAULT NULL,
  `backend_stability` json DEFAULT NULL,
  `policy_manifest` json DEFAULT NULL,
  `allow_remote_inference` tinyint(1) NOT NULL DEFAULT '0',
  `allow_tool_execution` tinyint(1) NOT NULL DEFAULT '0',
  `allow_file_access` tinyint(1) NOT NULL DEFAULT '0',
  `pricing_credits_per_1000` decimal(10,4) DEFAULT NULL,
  `credit_cost_multiplier` double NOT NULL DEFAULT '1',
  `pricing_model` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'per_token',
  `declaration_signature` text COLLATE utf8mb4_unicode_ci,
  `attested` tinyint(1) NOT NULL DEFAULT '0',
  `reputation_score` double NOT NULL DEFAULT '0.5' COMMENT 'Denormalized from reputations.score (W-042/D1prime). Canonical source per v2 storage design.',
  `rep_hourly_gain` decimal(8,4) NOT NULL DEFAULT '0.0000',
  `rep_hourly_window_start` timestamp NULL DEFAULT NULL,
  `credit_balance` decimal(15,4) NOT NULL DEFAULT '0.0000' COMMENT 'Denormalized from credits.balance (W-042/D1prime). Canonical source per v2 storage design.',
  `tasks_total` int unsigned NOT NULL DEFAULT '0' COMMENT 'Denormalized from reputations.tasks_total (D2prime-followup). Canonical per ADR-033 + W-042 v2 storage design.',
  `tasks_failed` int unsigned NOT NULL DEFAULT '0' COMMENT 'Denormalized from reputations.tasks_failed.',
  `avg_latency_ms` double NOT NULL DEFAULT '0' COMMENT 'Denormalized from reputations.avg_latency_ms.',
  `tasks_total_recent` int unsigned NOT NULL DEFAULT '0' COMMENT 'Phase A.2 / ADR-036: rolling-window task count (window = credit TTL)',
  `tasks_failed_recent` int unsigned NOT NULL DEFAULT '0' COMMENT 'Phase A.2 / ADR-036: rolling-window failure count',
  `avg_latency_ms_recent` double NOT NULL DEFAULT '0' COMMENT 'Phase A.2 / ADR-036: rolling-window EMA-smoothed latency',
  `recent_window_start` timestamp NULL DEFAULT NULL COMMENT 'Phase A.2 / ADR-036: when current rolling window opened',
  `free_credit_last_allocation_at` timestamp NULL DEFAULT NULL COMMENT 'Denormalized from credits.free_credit_last_allocation_at — 6h free-tier gate (issue #306).',
  `public_listing` tinyint(1) NOT NULL DEFAULT '0',
  `operator_url` varchar(256) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `operator_contact` varchar(256) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `operator_pubkey` varchar(80) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `operator_verified` tinyint(1) NOT NULL DEFAULT '0',
  `operator_trust_tier` varchar(16) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `status` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'active',
  `dormant_since` timestamp NULL DEFAULT NULL,
  `identity_key` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `lifetime_jobs` bigint unsigned NOT NULL DEFAULT '0',
  `pricing_effective_from` timestamp NULL DEFAULT NULL,
  `pricing_effective_until` timestamp NULL DEFAULT NULL,
  `last_seen` timestamp NULL DEFAULT NULL,
  `liveness_challenge` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `liveness_verified_at` timestamp NULL DEFAULT NULL,
  `node_token_hash` varchar(512) COLLATE utf8mb4_unicode_ci NOT NULL,
  `proxy_token_hash` varchar(60) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `node_hmac_key` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `max_concurrent` int unsigned NOT NULL,
  `tokens_per_min` int unsigned NOT NULL,
  `did_public_key` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `transport_method` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '#331 Phase A.1 / ADR-041: NAT-traversal tier method',
  `nat_type` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '#331 Phase A.1 / ADR-041: observed NAT type (full_cone, symmetric, etc.)',
  `transport_metadata` json DEFAULT NULL COMMENT '#331 Phase A.1 / ADR-041: forward-compat for transport_candidates[] + relay_endpoint',
  `transport_endpoint` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'spec v0.7.0: native IICP binary endpoint (iicp:// or iicpsec://, default port 9484)',
  `public_reachable` tinyint(1) NOT NULL DEFAULT '0' COMMENT '#326: true = appears in default /v1/discover; false = needs ?include_internal=true',
  `endpoint_verified_dead_at` timestamp NULL DEFAULT NULL,
  `sdk_language` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'SDK language tag: python / typescript / rust / etc. Free-form for future SDKs.',
  `implementation_name` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `implementation_version` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `sdk_compatibility_version` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `exposure_mode` varchar(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `cx_public_key` json DEFAULT NULL,
  `gossip_public_key` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `sdk_version` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'SDK package version (semver) — surfaced on /v1/discover.',
  `supported_receipt_profiles` json DEFAULT NULL,
  `auto_update_enabled` tinyint(1) DEFAULT NULL,
  `auto_update_interval_s` int unsigned DEFAULT NULL,
  `sdk_latest_seen` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `sdk_update_last_checked_at` timestamp NULL DEFAULT NULL,
  `sdk_update_error_class` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `nodes_available_index` (`available`),
  KEY `nodes_last_seen_index` (`last_seen`),
  KEY `nodes_region_index` (`region`),
  KEY `nodes_discover_idx` (`available`,`status`,`last_seen`),
  KEY `nodes_recent_window_start_index` (`recent_window_start`),
  KEY `nodes_public_reachable_last_seen_idx` (`public_reachable`,`last_seen`),
  KEY `nodes_operator_pubkey_idx` (`operator_pubkey`),
  KEY `nodes_endpoint_verified_dead_at_index` (`endpoint_verified_dead_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `operators` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `operator_pubkey` varchar(80) COLLATE utf8mb4_unicode_ci NOT NULL,
  `identity_status` varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'active',
  `successor_operator_pubkey_sha256` char(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `rotation_epoch` int unsigned DEFAULT NULL,
  `identity_revoked_at` timestamp NULL DEFAULT NULL,
  `identity_reason_class` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `display_name` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `attested_created_at` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `operator_integrity_hash` char(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `first_seen_ms` bigint unsigned DEFAULT NULL,
  `ordinal` bigint unsigned DEFAULT NULL,
  `tier` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `badge` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `provenance` json DEFAULT NULL,
  `terms_version` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `terms_accepted_at` timestamp NULL DEFAULT NULL,
  `dpa_version` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `dpa_accepted_at` timestamp NULL DEFAULT NULL,
  `acceptance_method` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `acceptance_nonce_sha256` char(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `operators_operator_pubkey_unique` (`operator_pubkey`),
  KEY `operators_identity_status_idx` (`identity_status`,`updated_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `policy_key_lifecycle_records` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `policy_key_sha256` char(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `status` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'active',
  `rotation_epoch` int unsigned DEFAULT NULL,
  `revoked_at` timestamp NULL DEFAULT NULL,
  `revocation_reason_class` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `superseded_by_policy_key_sha256` char(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `evidence_ref` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `policy_key_lifecycle_records_policy_key_sha256_unique` (`policy_key_sha256`),
  KEY `policy_key_lifecycle_status_idx` (`status`,`updated_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `probe_tokens` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `token_hash` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `label` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `region` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `expires_at` timestamp NULL DEFAULT NULL,
  `last_seen_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `probe_tokens_token_hash_unique` (`token_hash`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `proxy_telemetry` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `node_id` varchar(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `proxy_node_id` varchar(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `time_bucket` bigint unsigned NOT NULL,
  `latency_ms_observed` double NOT NULL,
  `tokens_observed` int unsigned NOT NULL DEFAULT '0',
  `status` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'success',
  `qos_advertised` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `qos_met` tinyint(1) NOT NULL DEFAULT '1',
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `proxy_telemetry_dedup` (`node_id`,`proxy_node_id`,`time_bucket`),
  KEY `proxy_telemetry_node_id_index` (`node_id`),
  KEY `proxy_telemetry_proxy_node_id_index` (`proxy_node_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `replicas` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `replica_id` char(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `did` varchar(253) COLLATE utf8mb4_unicode_ci NOT NULL,
  `endpoint` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `trust_tier` varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'low',
  `status` varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'active' COMMENT 'Phase A.3: active/dormant/archived/decommissioned (lifecycle state)',
  `replica_token_hash` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `expires_at` timestamp NOT NULL,
  `last_seen_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `replicas_replica_id_unique` (`replica_id`),
  UNIQUE KEY `replicas_did_unique` (`did`),
  KEY `replicas_trust_tier_index` (`trust_tier`),
  KEY `replicas_status_index` (`status`),
  KEY `replicas_last_seen_at_index` (`last_seen_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `reputations` (
  `node_id` char(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `score` double NOT NULL DEFAULT '0.5',
  `tasks_total` int unsigned NOT NULL DEFAULT '0',
  `tasks_failed` int unsigned NOT NULL DEFAULT '0',
  `completed_tasks_count` bigint unsigned NOT NULL DEFAULT '0',
  `avg_latency_ms` double NOT NULL DEFAULT '0',
  `observed_latency_ms` double DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`node_id`),
  CONSTRAINT `reputations_node_id_foreign` FOREIGN KEY (`node_id`) REFERENCES `nodes` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
SET FOREIGN_KEY_CHECKS=1;
